#############################################################################
# Makefile for building: icp
# Generated by qmake (3.1) (Qt 5.9.7)
# Autor: Tomáš Blaha
# Project:  ICP_Project.pro
# Projekt je z části generován nástrojem qmake a dopsán
#############################################################################



# Překladač a potřebné flagy a includy
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB

CXXFLAGS      = -pipe -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++11 -W -D_REENTRANT -fPIC $(DEFINES)

INCPATH       = -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -I $(TMP_DIR)
MOC_INCLUDES = -I/usr/lib64/qt5/mkspecs/linux-g++ -I. -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include


LIBS    = -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread
# použité nástroje
DEL_FILE      = rm -f
MKDIR         = mkdir -p
ZIP 	      = zip -r
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
DEL_DIR       = rm -rf
MOVE          = mv -f

# výsledný program
TARGET        = icp
# adresáře
OBJECTS_DIR   = obj
SRC_DIR = src
MODELS_DIR = $(SRC_DIR)/Models
VIEWS_DIR = $(SRC_DIR)/Views
UI_DIR = views
DOC_DIR = doc
TINYXML_DIR = $(SRC_DIR)/tinyxml
TMP_DIR = tmp
PACK_DIR = xblaha31-xwawre00
EXAMPLES_DIR = examples

# hlavičkový soubor generovaný při překladu
MOC_PREDEFS_HEADER = $(TMP_DIR)/moc_predefs.h



# zdrojové soubory
SOURCES = $(MODELS_DIR)/basemodel.cpp \
		$(MODELS_DIR)/buslinemodel.cpp \
		$(MODELS_DIR)/busmodel.cpp \
		$(MODELS_DIR)/busstopmodel.cpp \
		$(MODELS_DIR)/clockmodel.cpp \
		$(MODELS_DIR)/mapmodel.cpp \
		$(MODELS_DIR)/pathmodel.cpp \
		$(MODELS_DIR)/pointmodel.cpp \
		$(MODELS_DIR)/streetmodel.cpp \
		$(MODELS_DIR)/timetablemodel.cpp \
		$(VIEWS_DIR)/busdetailview.cpp \
		$(VIEWS_DIR)/busstopdetailview.cpp \
		$(VIEWS_DIR)/busstopview.cpp \
		$(VIEWS_DIR)/busview.cpp \
		$(VIEWS_DIR)/clockdetailview.cpp \
		$(VIEWS_DIR)/clockview.cpp \
		$(VIEWS_DIR)/detourdetailview.cpp \
		$(VIEWS_DIR)/mapview.cpp \
		$(VIEWS_DIR)/streetdetailview.cpp \
		$(VIEWS_DIR)/streetview.cpp \
		$(SRC_DIR)/TimeLib.cpp \
		$(SRC_DIR)/main.cpp \
		$(SRC_DIR)/mainwindow.cpp \
		$(SRC_DIR)/mapcreator.cpp \
		$(TINYXML_DIR)/tinyxml/tinystr.cpp \
		$(TINYXML_DIR)/tinyxml/tinyxml.cpp \
		$(TINYXML_DIR)/tinyxml/tinyxmlerror.cpp \
		$(TINYXML_DIR)/tinyxmlparser.cpp \
		$(TMP_DIR)/moc_busdetailview.cpp \
		$(TMP_DIR)/moc_busstopdetailview.cpp \
		$(TMP_DIR)/moc_clockdetailview.cpp \
		$(TMP_DIR)/moc_clockview.cpp \
		$(TMP_DIR)/moc_detourdetailview.cpp \
		$(TMP_DIR)/moc_mapview.cpp \
		$(TMP_DIR)/moc_streetdetailview.cpp \
		$(TMP_DIR)/moc_mainwindow.cpp

# objekty
OBJECTS  = $(OBJECTS_DIR)/basemodel.o \
		$(OBJECTS_DIR)/buslinemodel.o \
		$(OBJECTS_DIR)/busmodel.o \
		$(OBJECTS_DIR)/busstopmodel.o \
		$(OBJECTS_DIR)/clockmodel.o \
		$(OBJECTS_DIR)/mapmodel.o \
		$(OBJECTS_DIR)/pathmodel.o \
		$(OBJECTS_DIR)/pointmodel.o \
		$(OBJECTS_DIR)/streetmodel.o \
		$(OBJECTS_DIR)/timetablemodel.o \
		$(OBJECTS_DIR)/TimeLib.o \
		$(OBJECTS_DIR)/busdetailview.o \
		$(OBJECTS_DIR)/busstopdetailview.o \
		$(OBJECTS_DIR)/busstopview.o \
		$(OBJECTS_DIR)/busview.o \
		$(OBJECTS_DIR)/clockdetailview.o \
		$(OBJECTS_DIR)/clockview.o \
		$(OBJECTS_DIR)/detourdetailview.o \
		$(OBJECTS_DIR)/mapview.o \
		$(OBJECTS_DIR)/streetdetailview.o \
		$(OBJECTS_DIR)/streetview.o \
		$(OBJECTS_DIR)/main.o \
		$(OBJECTS_DIR)/mainwindow.o \
		$(OBJECTS_DIR)/mapcreator.o \
		$(OBJECTS_DIR)/tinystr.o \
		$(OBJECTS_DIR)/tinyxml.o \
		$(OBJECTS_DIR)/tinyxmlerror.o \
		$(OBJECTS_DIR)/tinyxmlparser.o \
		$(OBJECTS_DIR)/moc_busdetailview.o \
		$(OBJECTS_DIR)/moc_busstopdetailview.o \
		$(OBJECTS_DIR)/moc_clockdetailview.o \
		$(OBJECTS_DIR)/moc_clockview.o \
		$(OBJECTS_DIR)/moc_detourdetailview.o \
		$(OBJECTS_DIR)/moc_mapview.o \
		$(OBJECTS_DIR)/moc_streetdetailview.o \
		$(OBJECTS_DIR)/moc_mainwindow.o
# překlad programu
all: $(TARGET)  
	
$(TARGET): $(OBJECTS_DIR) $(TMP_DIR) uic_files moc_files objects
	$(CXX) $(LFLAGS) -o $(TARGET) -I $(TMP_DIR) $(OBJECTS) $(LIBS)

# vytvoření adresáře tmp
$(OBJECTS_DIR):
	$(MKDIR) $(OBJECTS_DIR)

# vytvoření adresáře tmp
$(TMP_DIR):
	$(MKDIR) $(TMP_DIR)

# vygenerování hlavičkových souborů 
uic_files: $(TMP_DIR) $(TMP_DIR)/ui_mainwindow.h

$(TMP_DIR)/ui_mainwindow.h: $(UI_DIR)/mainwindow.ui
	/usr/lib64/qt5/bin/uic  $< -o $@
# vygenerování moc souborů
moc_files:  $(TMP_DIR)/moc_busdetailview.cpp $(TMP_DIR)/moc_busstopdetailview.cpp $(TMP_DIR)/moc_clockdetailview.cpp $(TMP_DIR)/moc_clockview.cpp $(TMP_DIR)/moc_detourdetailview.cpp $(TMP_DIR)/moc_mapview.cpp $(TMP_DIR)/moc_streetdetailview.cpp $(TMP_DIR)/moc_mainwindow.cpp


# vygenerování objektů
objects: $(OBJECTS_DIR) $(OBJECTS)

# spuštění programu
run: $(TARGET)
	./$(TARGET)

# vygenerování dokumentace
doxygen:
	$(MKDIR) $(DOC_DIR)
	doxygen src/Doxyfile
	$(MOVE) html $(DOC_DIR)
# smazaní vygenerovaných souborů
clean:
	$(DEL_DIR) $(TMP_DIR)
	$(DEL_DIR) $(OBJECTS_DIR)
	$(DEL_FILE) $(TARGET)
	$(DEL_DIR) $(DOC_DIR)
# zabalení k doevzdání
pack: clean
	$(MKDIR) $(PACK_DIR)
	$(COPY_FILE) README.txt $(PACK_DIR)
	$(COPY_FILE) ICP_Project.pro $(PACK_DIR)
	$(COPY_FILE) Makefile $(PACK_DIR)
	$(COPY_DIR) $(SRC_DIR) $(PACK_DIR)
	$(COPY_DIR) $(UI_DIR) $(PACK_DIR) 
	$(COPY_DIR) $(EXAMPLES_DIR) $(PACK_DIR)
	$(ZIP) $(PACK_DIR).zip $(PACK_DIR)
	$(DEL_DIR) $(PACK_DIR)	

# vygenerování moc souborů
$(MOC_PREDEFS_HEADER): $(TMP_DIR) /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++11 -Wall -W -dM -E -o $(MOC_PREDEFS_HEADER) /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

$(TMP_DIR)/moc_busdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER)  $(VIEWS_DIR)/busdetailview.h -o $(TMP_DIR)/moc_busdetailview.cpp

$(TMP_DIR)/moc_busstopdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/busstopdetailview.h -o $(TMP_DIR)/moc_busstopdetailview.cpp

$(TMP_DIR)/moc_clockdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/clockdetailview.h -o $(TMP_DIR)/moc_clockdetailview.cpp

$(TMP_DIR)/moc_clockview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/clockview.h -o $(TMP_DIR)/moc_clockview.cpp

$(TMP_DIR)/moc_detourdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/detourdetailview.h -o $(TMP_DIR)/moc_detourdetailview.cpp

$(TMP_DIR)/moc_mapview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/mapview.h -o $(TMP_DIR)/moc_mapview.cpp

$(TMP_DIR)/moc_streetdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/streetdetailview.h -o $(TMP_DIR)/moc_streetdetailview.cpp

$(TMP_DIR)/moc_mainwindow.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(SRC_DIR)/mainwindow.h -o $(TMP_DIR)/moc_mainwindow.cpp

# vygenerování objektů
$(OBJECTS_DIR)/%.o:  $(MODELS_DIR)/%.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<


$(OBJECTS_DIR)/%.o: $(VIEWS_DIR)/%.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

$(OBJECTS_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

$(OBJECTS_DIR)/%.o: $(TINYXML_DIR)/%.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

$(OBJECTS_DIR)/%.o: $(TMP_DIR)/%.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<




