#############################################################################
# Makefile for building: icp
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  ICP_Project.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile ICP_Project.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -I $(TMP_DIR)
MOC_INCLUDES = -I/usr/lib64/qt5/mkspecs/linux-g++ -I. -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/local/include/c++/7.5.0 -I/usr/local/include/c++/7.5.0/x86_64-linux -I/usr/local/include/c++/7.5.0/backward -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-linux/7.5.0/include-fixed -I/usr/include

DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R

DEL_FILE      = rm -f

DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f



LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          =  -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
TARGET        = icp

OBJECTS_DIR   = obj
SRC_DIR = src
MODELS_DIR = $(SRC_DIR)/Models
VIEWS_DIR = $(SRC_DIR)/Views
UI_DIR = views
DOC_DIR = doc
TINYXML_DIR = $(SRC_DIR)/tinyxml
TMP_DIR = tmp
MOC_PREDEFS_HEADER = $(TMP_DIR)/moc_predefs.h


	

SOURCES = $(MODELS_DIR)/basemodel.cpp \
		$(MODELS_DIR)/buslinemodel.cpp \
		$(MODELS_DIR)/busmodel.cpp \
		$(MODELS_DIR)/busstopmodel.cpp \
		$(MODELS_DIR)/clockmodel.cpp \
		$(MODELS_DIR)/mapmodel.cpp \
		$(MODELS_DIR)/pathmodel.cpp \
		$(MODELS_DIR)/pointmodel.cpp \
		$(MODELS_DIR)/streetmodel.cpp \
		$(MODELS_DIR)/timetablemodel.cpp \
		$(VIEWS_DIR)/busdetailview.cpp \
		$(VIEWS_DIR)/busstopdetailview.cpp \
		$(VIEWS_DIR)/busstopview.cpp \
		$(VIEWS_DIR)/busview.cpp \
		$(VIEWS_DIR)/clockdetailview.cpp \
		$(VIEWS_DIR)/clockview.cpp \
		$(VIEWS_DIR)/detourdetailview.cpp \
		$(VIEWS_DIR)/mapview.cpp \
		$(VIEWS_DIR)/streetdetailview.cpp \
		$(VIEWS_DIR)/streetview.cpp \
		$(SRC_DIR)/TimeLib.cpp \
		$(SRC_DIR)/main.cpp \
		$(SRC_DIR)/mainwindow.cpp \
		$(SRC_DIR)/mapcreator.cpp \
		$(TINYXML_DIR)/tinyxml/tinystr.cpp \
		$(TINYXML_DIR)/tinyxml/tinyxml.cpp \
		$(TINYXML_DIR)/tinyxml/tinyxmlerror.cpp \
		$(TINYXML_DIR)/tinyxmlparser.cpp \
		$(TMP_DIR)/moc_busdetailview.cpp \
		$(TMP_DIR)/moc_busstopdetailview.cpp \
		$(TMP_DIR)/moc_clockdetailview.cpp \
		$(TMP_DIR)/moc_clockview.cpp \
		$(TMP_DIR)/moc_detourdetailview.cpp \
		$(TMP_DIR)/moc_mapview.cpp \
		$(TMP_DIR)/moc_streetdetailview.cpp \
		$(TMP_DIR)/moc_mainwindow.cpp
OBJECTS  = $(OBJECTS_DIR)/basemodel.o \
		$(OBJECTS_DIR)/buslinemodel.o \
		$(OBJECTS_DIR)/busmodel.o \
		$(OBJECTS_DIR)/busstopmodel.o \
		$(OBJECTS_DIR)/clockmodel.o \
		$(OBJECTS_DIR)/mapmodel.o \
		$(OBJECTS_DIR)/pathmodel.o \
		$(OBJECTS_DIR)/pointmodel.o \
		$(OBJECTS_DIR)/streetmodel.o \
		$(OBJECTS_DIR)/timetablemodel.o \
		$(OBJECTS_DIR)/TimeLib.o \
		$(OBJECTS_DIR)/busdetailview.o \
		$(OBJECTS_DIR)/busstopdetailview.o \
		$(OBJECTS_DIR)/busstopview.o \
		$(OBJECTS_DIR)/busview.o \
		$(OBJECTS_DIR)/clockdetailview.o \
		$(OBJECTS_DIR)/clockview.o \
		$(OBJECTS_DIR)/detourdetailview.o \
		$(OBJECTS_DIR)/mapview.o \
		$(OBJECTS_DIR)/streetdetailview.o \
		$(OBJECTS_DIR)/streetview.o \
		$(OBJECTS_DIR)/main.o \
		$(OBJECTS_DIR)/mainwindow.o \
		$(OBJECTS_DIR)/mapcreator.o \
		$(OBJECTS_DIR)/tinystr.o \
		$(OBJECTS_DIR)/tinyxml.o \
		$(OBJECTS_DIR)/tinyxmlerror.o \
		$(OBJECTS_DIR)/tinyxmlparser.o \
		$(OBJECTS_DIR)/moc_busdetailview.o \
		$(OBJECTS_DIR)/moc_busstopdetailview.o \
		$(OBJECTS_DIR)/moc_clockdetailview.o \
		$(OBJECTS_DIR)/moc_clockview.o \
		$(OBJECTS_DIR)/moc_detourdetailview.o \
		$(OBJECTS_DIR)/moc_mapview.o \
		$(OBJECTS_DIR)/moc_streetdetailview.o \
		$(OBJECTS_DIR)/moc_mainwindow.o

all: $(OBJECTS_DIR) $(TMP_DIR)  uic_files moc_files $(OBJECTS)  
	$(CXX) $(LFLAGS) -o $(TARGET) -I $(TMP_DIR) $(OBJECTS) $(OBJCOMP) $(LIBS)
$(OBJECTS_DIR):
	mkdir -p $(OBJECTS_DIR)

$(TMP_DIR):
	mkdir -p $(TMP_DIR)
uic_files: $(TMP_DIR) $(TMP_DIR)/ui_mainwindow.h

$(TMP_DIR)/ui_mainwindow.h: $(UI_DIR)/mainwindow.ui
	/usr/lib64/qt5/bin/uic  $< -o $@

moc_files:  $(TMP_DIR)/moc_busdetailview.cpp $(TMP_DIR)/moc_busstopdetailview.cpp $(TMP_DIR)/moc_clockdetailview.cpp $(TMP_DIR)/moc_clockview.cpp $(TMP_DIR)/moc_detourdetailview.cpp $(TMP_DIR)/moc_mapview.cpp $(TMP_DIR)/moc_streetdetailview.cpp $(TMP_DIR)/moc_mainwindow.cpp



objects: $(OBJECTS_DIR) $(OBJECTS)


doc:
	mkdir -p $(DOC_DIR)
	doxygen src/Doxyfile
	mv html $(DOC_DIR)





	







clean:
	rm -rf $(TMP_DIR)
	rm -rf $(OBJECTS_DIR)
	rm -f $(TARGET)

$(MOC_PREDEFS_HEADER): $(TMP_DIR) /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++11 -Wall -W -dM -E -o $(MOC_PREDEFS_HEADER) /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

$(TMP_DIR)/moc_busdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER)  $(VIEWS_DIR)/busdetailview.h -o $(TMP_DIR)/moc_busdetailview.cpp

$(TMP_DIR)/moc_busstopdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/busstopdetailview.h -o $(TMP_DIR)/moc_busstopdetailview.cpp

$(TMP_DIR)/moc_clockdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/clockdetailview.h -o $(TMP_DIR)/moc_clockdetailview.cpp

$(TMP_DIR)/moc_clockview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/clockview.h -o $(TMP_DIR)/moc_clockview.cpp

$(TMP_DIR)/moc_detourdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/detourdetailview.h -o $(TMP_DIR)/moc_detourdetailview.cpp

$(TMP_DIR)/moc_mapview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/mapview.h -o $(TMP_DIR)/moc_mapview.cpp

$(TMP_DIR)/moc_streetdetailview.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(VIEWS_DIR)/streetdetailview.h -o $(TMP_DIR)/moc_streetdetailview.cpp

$(TMP_DIR)/moc_mainwindow.cpp: $(TMP_DIR) $(MOC_PREDEFS_HEADER)
	/usr/lib64/qt5/bin/moc $(DEFINES) --include $(MOC_PREDEFS_HEADER) $(MOC_INCLUDES) $(SRC_DIR)/mainwindow.h -o $(TMP_DIR)/moc_mainwindow.cpp




$(OBJECTS_DIR)/%.o:  $(MODELS_DIR)/%.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<


$(OBJECTS_DIR)/%.o: $(VIEWS_DIR)/%.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

$(OBJECTS_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

$(OBJECTS_DIR)/%.o: $(TINYXML_DIR)/%.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

$(OBJECTS_DIR)/%.o: $(TMP_DIR)/%.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<




